services:
  - type: web
    name: learning-english-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5010
    healthCheckPath: /health
    domains:
      - backend.learning-english.iaproject.fr

